# fly.toml app configuration file generated for tradingcards on 2023-10-21T15:43:48-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tradingcards"
primary_region = "ord"

[env]
ASPNETCORE_URLS="http://+:8080"

[build]
  image = "travismc6/tradingcards:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
